# Site settings
title: "ESE 2015 | iFSR"
email: ese@ifsr.de
emailfsr: fsr@ifsr.de
<<<<<<< HEAD
description: > # this means to ignore newlines until "baseurl:"
  Die offizielle Seite der ESE 2015
baseurl: "/ese-webseite" # the subpath of your site, e.g. /blog/
url: "https://fsr.github.io" # the base hostname & protocol for your site
=======
baseurl: "/2015" # the subpath of your site, e.g. /blog/
url: "https://ese.ifsr.de" # the base hostname & protocol for your site
>>>>>>> metatags
twitter_username: ifsr
github_username:  fsr
color: "#573B75"

# Global Metatags
metatag:
  de:
    description: "Die offizielle Seite der ESE 2015. Hier findet Ihr alle wichtigen Informationen 端ber die Erst Semester Einf端hrung der Informatik an der TU Dresden."
    abstract:
    keywords:
    "og:title": "ESE 2015 | iFSR"
    "og:description": "Die offizielle Seite der ESE 2015. Hier findet Ihr alle wichtigen Informationen 端ber die Erst Semester Einf端hrung der Informatik an der TU Dresden."
    "og:locale":
    "og:locale:alternate":
    "og:image":
    "og:image:secure:url":
    "og:type":
    "og:site_name":
    "og:url":
    "og:type":
    HandheldFriendly: true
  en:
    description:
    abstract:
    keywords:
    "og:title": "ESE 2015 | iFSR"
    "og:description":
    "og:locale":
    "og:ocale-alternate":
    "og:image":
    "og:secure-url":
    "og:type":
    "og:site_name":
    "og:url":
    "og:type":
    HandheldFriendly: true

# Build settings
markdown: kramdown

exclude:
  - .c9
  - .git

permalink: none

compress_html:
  clippings: all
  comments: []
  endings: []
  profile: false
  ignore:
    envs: []

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "en"
      type: "en-posts"
    values:
      layout: "en-post"
  -
    scope:
      path: "en"
      type: "en"
    values:
      layout: "en-page"

sass:
  style: :compressed

collections:
  news:
  sidebar:
  en-news:
  en-sidebar:
  en:
    output: true
    permalink: en/:path:output_ext
